services:
  mem0_store:
    image: qdrant/qdrant
    expose:
      - "6333"
    volumes:
      - mem0_storage:/qdrant/storage
    restart: unless-stopped

  openmemory-mcp:
    image: mem0/openmemory-mcp
    build: api/
    environment:
      - USER
      - API_KEY
      - OPENAI_API_KEY
    env_file:
      - api/.env
    depends_on:
      - mem0_store
    expose:
      - "8765"
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8765 --workers 4"
    restart: unless-stopped

  openmemory-ui:
    build:
      context: ui/
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_USER_ID: ${USER}
    expose:
      - "3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_USER_ID=${USER}
    depends_on:
      - openmemory-mcp
    restart: unless-stopped

volumes:
  mem0_storage:
